name: Build documentation

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  create-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: mattnotmitt/doxygen-action@edge
      - run: |
          mkdir -p web/content/dox
          sudo mv doc/html/* web/content/dox
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build sysex-configurator
        run: |
          cd sysex-configurator
          npm install
          npm run build
          cp -rf dist ../web/static/sysex-configurator
        working-directory: web
      - name: Build
        run: |
          hugo mod get -u
          hugo --minify
        working-directory: web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'web/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
